name: biobuddy
channels:
  - opensim-org
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - pip
  - pandas
  - graphviz
  - opensim=4.5.1
  - biorbd=1.11.2=py311h52b9107_1
  - deepdiff
  - pinocchio
  - pip:
      - scipy==1.17.0
      - numpy==2.4.1
      - lxml
      - ezc3d
      - matplotlib
      - plotly
      - pytest
      - pytest-cov
      - codecov
