#!/bin/bash
#
# Point a conda environment at a locally built OpenSim, so that
# `import opensim` works without manually exporting PYTHONPATH/LD_LIBRARY_PATH
# every time.
#
# It writes conda "activate.d"/"deactivate.d" hooks into the CURRENTLY ACTIVE
# conda environment. Those hooks export PYTHONPATH/LD_LIBRARY_PATH
# automatically every time you `conda activate <env>`, and unset them again
# on `conda deactivate` -- no manual exporting needed after this.
#
# --- Usage ---
#
# 1. Build OpenSim first (only needs to be done once, or again after pulling
#    changes to install_opensim.sh), e.g.:
#
#      conda activate biobuddy
#      bash .github/workflows/install_opensim.sh "$CONDA_PREFIX"
#
#    This creates ./opensim/opensim_core_install relative to wherever you ran
#    the build command from.
#
# 2. With that SAME conda env still active, run this script from the same
#    directory, pointing it at the install directory if it isn't the default:
#
#      bash .github/workflows/configure_opensim_env.sh [path/to/opensim_core_install]
#
#    (defaults to ./opensim/opensim_core_install if no argument is given)
#
# 3. Re-activate the env so the hook actually runs, then test:
#
#      conda deactivate
#      conda activate biobuddy
#      python -c "import opensim; print(opensim.GetVersion())"
#
# Re-run this script any time OpenSim gets rebuilt or moved to a new path.

set -e

OPENSIM_INSTALL="${1:-$(pwd)/opensim/opensim_core_install}"

if [ -z "$CONDA_PREFIX" ]; then
    echo "Error: no conda environment is active. Run 'conda activate <env>' first." >&2
    exit 1
fi

if [ ! -d "$OPENSIM_INSTALL" ]; then
    echo "Error: OpenSim install directory not found: $OPENSIM_INSTALL" >&2
    echo "Pass the path explicitly, e.g.: bash $0 /path/to/opensim_core_install" >&2
    exit 1
fi

# Find the "opensim" python package directory (the folder containing
# __init__.py) so we can put its PARENT on PYTHONPATH.
OPENSIM_PY_INIT=$(find "$OPENSIM_INSTALL" -path "*/opensim/__init__.py" | head -n1)
if [ -z "$OPENSIM_PY_INIT" ]; then
    echo "Error: could not find an 'opensim/__init__.py' under $OPENSIM_INSTALL" >&2
    echo "Did the build finish and install successfully (with BUILD_PYTHON_WRAPPING=on)?" >&2
    exit 1
fi
OPENSIM_PY_PKG_PARENT=$(dirname "$(dirname "$OPENSIM_PY_INIT")")

# Collect every directory containing a compiled shared library (OpenSim's own
# libs plus the bundled Simbody ones), so the compiled extension modules can
# resolve them at runtime.
LIB_DIRS=$(find "$OPENSIM_INSTALL" -name "*.so*" -exec dirname {} \; | sort -u | paste -sd:)

ACTIVATE_DIR="$CONDA_PREFIX/etc/conda/activate.d"
DEACTIVATE_DIR="$CONDA_PREFIX/etc/conda/deactivate.d"
mkdir -p "$ACTIVATE_DIR" "$DEACTIVATE_DIR"

cat > "$ACTIVATE_DIR/opensim.sh" <<EOF
# Auto-generated by configure_opensim_env.sh -- do not edit by hand,
# re-run the script instead if OpenSim gets rebuilt or moved.
export _OLD_PYTHONPATH="\$PYTHONPATH"
export _OLD_LD_LIBRARY_PATH="\$LD_LIBRARY_PATH"
export PYTHONPATH="$OPENSIM_PY_PKG_PARENT:\$PYTHONPATH"
export LD_LIBRARY_PATH="$LIB_DIRS:\$CONDA_PREFIX/lib:\$LD_LIBRARY_PATH"
EOF

cat > "$DEACTIVATE_DIR/opensim.sh" <<'EOF'
# Auto-generated by configure_opensim_env.sh
export PYTHONPATH="$_OLD_PYTHONPATH"
export LD_LIBRARY_PATH="$_OLD_LD_LIBRARY_PATH"
unset _OLD_PYTHONPATH _OLD_LD_LIBRARY_PATH
EOF

echo "Done."
echo "  OpenSim python package dir: $OPENSIM_PY_PKG_PARENT"
echo "  Library dirs:               $LIB_DIRS"
echo ""
echo "Now run this to make it take effect:"
echo "  conda deactivate && conda activate $(basename "$CONDA_PREFIX")"
echo '  python -c "import opensim; print(opensim.GetVersion())"'
